### ISSUE TITLE
Question about incrementing refresh token count

### ISSUE THREAD

**Issue by miller-productions** [rkotze/rkotze.github.io#39]
Re: _posts/2019-11-18-jwt-apollo-server-graphql.md

Hi Richard,

Hey, I was just reading your article here... 

https://www.richardkotze.com/coding/json-web-tokens-using-apollo-graphql

I'm wondering when the 'count' gets incremented and stored in the user repo?

I assume you would do this inside // module `set-tokens`?

```
const { sign } = require("jsonwebtoken");

function setTokens(user) {
  const sevenDays = 60 * 60 * 24 * 7 * 1000;
  const fifteenMins = 60 * 15 * 1000;
  const accessUser = {
    id: user.id
  };
  const accessToken = sign(
    { user: accessUser },
    "<your secret key for access token>",
    {
      expiresIn: fifteenMins
    }
  );
  const refreshUser = {
    id: user.id,
    count: user.tokenCount    <<<<<<   perhaps count gets incremented here?
  };
  const refreshToken = sign(
    { user: refreshUser },
    "<your secret key for refresh token>",
    {
      expiresIn: sevenDays
    }
  );

  return { accessToken, refreshToken };
}
```

In the current example, you don't appear to increment it anywhere?

Anyway, just thought I would ask.

Thanks for the excellent article, it has definitely been helpful for me to learn a few new ideas about using tokens with graphql.

Cheers,
Dan

**Comment by miller-productions** [comment]
Hmmm, never mind. I think I understand how you are using count a bit more now...

It looks like the count stays the same most of the time and if you ever want to invalidate the refresh token, you simply increment the count in the user repo via some admin interface?

**Comment by rkotze** [comment]
@miller-productions Glad, you found the post helpful and thanks for the question. 

Just to confirm you are correct, anytime an admin of the system wants to invalidate a user's session we can do this by incrementing the value. Which is stored in a db user table for example.  When the `validateRefreshToken` is run, the token will be invalid and force the user to log-in.

Hope that helps.

```javascript
const decodedRefreshToken = validateRefreshToken(refreshToken);
  if (decodedRefreshToken && decodedRefreshToken.user) {
    // valid refresh token
    const user = await userRepo.get({ userId: decodedRefreshToken.user.id });
    // valid user and user token not invalidated
    if (!user || user.tokenCount !== decodedRefreshToken.user.count)
      return next();
    req.user = decodedRefreshToken.user;
    // refresh the tokens
    const userTokens = setTokens(user);
    res.set({
      "Access-Control-Expose-Headers": "x-access-token,x-refresh-token",
      "x-access-token": userTokens.accessToken,
      "x-refresh-token": userTokens.refreshToken
    });
    return next();
  }
```
