### ISSUE TITLE
might need to set 'expires' on refresh token cookie?

### ISSUE THREAD

**Issue by miller-productions** [rkotze/rkotze.github.io#40]
Hi Richard,

I'm continuing to enjoy your series on JWT tokens, thanks again.

Hey, I just noticed on this page... _posts/2019-12-02-jwt-secure-apollo-client-graphql.md

When you set the cookie holding the refresh token, there is no expiry set on this token. Hence, it gets created as a session token.

Should this possibly have an expiry on it, similar to the expiry in the refresh token itself so that it doesn't get cleared when the client closes the browser session?

Regards,
Dan

**Comment by rkotze** [comment]
Hi Dan

You could set an expiry date on the recycle cookie, but I guess you might want to let the user opt-in to keep their session after closing the browser. Browsers do restore the user's last session as well provided they have set it.

IMO the user should manage if their session stays active.
